business_name: RZZT CIC
business_information:
    - UK company number 10951485
base_url: "https://rzzt.io/accounts"
functional_currency: USD
accounts:
    -
        name: Miscellaneous receivables
        type: Asset
    -
        name: Patreon
        type: Asset
    -
        name: PayPal
        type: Asset
    -
        name: Prepaid invoices
        type: Asset
    -
        name: Unliquidated assets
        type: Asset
    -
        name: Accounts payable
        type: Liability
    -
        name: Patreon contributions
        type: Income
    -
        name: PayPal contributions
        type: Income
    -
        name: Unliquidated contributions
        type: Income
    -
        name: Administrative costs
        type: Expense
    -
        name: Contractor invoices
        type: Expense
    -
        name: Patreon fees
        type: Expense
    -
        name: PayPal fees
        type: Expense
currencies:
    -
        name: United States Dollars
        code: USD
        symbol: $
